name: Azure VM Deployment

on:
  push:
    branches:
      - main  # Modify this to match your branch name

env:
  using: 'node16'
  main: 'main.js'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to Azure VM and run script
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} <Joineer>@13.95.131.205 "sudo ./testing.sh"
